name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        run: rustup toolchain install stable

      - name: Install ESP tools
        working-directory: /tmp
        run: |
          cargo +stable install espup --locked
          cargo +stable install espflash --locked
          cargo +stable install probe-rs-tools --locked

      - name: Install ESP Rust toolchain
        run: |
          espup install

      - name: Load ESP environment
        run: |
          cat "$HOME/export-esp.sh" >> "$GITHUB_ENV"

      - name: Verify ESP toolchain
        run: |
          source "$HOME/export-esp.sh"
          echo "PATH=$PATH"
          which rustc
          which xtensa-esp32-elf-gcc
          rustc --version
          xtensa-esp32-elf-gcc --version

      - name: Show versions
        run: |
          rustc --version
          cargo --version
          espflash --version

      - name: Run Checks
        run: |
          source "$HOME/export-esp.sh"
          cargo check

      - name: Try Build
        run: |
          source "$HOME/export-esp.sh"
          cargo build
